### ISSUE TITLE
Publish actions running in forked repositories

### ISSUE THREAD

**Issue by Defkon1** [marcominerva/OperationResults#38]
The three publish-related actions contained in the repository should run only on the main repository, not on the forked ones.

The owner of a forked repository could disable all actions, but in this way the Linter and CodeQL actions will be disabled too.

I propose to add an owner check in the publishing actions, so they will be skipped on forked repositories.

E.g.

```
jobs:
  publish:
    name: Publish on NuGet
    runs-on: ubuntu-latest
    if: github.repository_owner == 'marcominerva'

```
